#!/bin/bash 
sudo apt install -y cockpit
sudo systemctl enable --now cockpit.socket
sudo bash -c 'echo "AllowRoot=true" >> /etc/cockpit/cockpit.conf.d/50-allow-root.conf'
sudo systemctl restart cockpit
