#!/bin/bash
# Create the docker-compose.yml file
cat <<EOF > docker-compose.yml
version: '3'
services:
  guacd:
    restart: always
    image: guacamole/guacd
  guacamole-server:
    restart: always
    image: guacamole/guacamole
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      - GUACD_HOSTNAME=guacd
      - MYSQL_HOSTNAME=database
      - MYSQL_DATABASE=guacamole
      - MYSQL_USER=guac
      - MYSQL_PASSWORD=guacpassword
  database:
    restart: always
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=guacamole
      - MYSQL_USER=guac
      - MYSQL_PASSWORD=guacpassword
    volumes:
      - ./db:/var/lib/mysql
EOF
# Start Docker containers
docker-compose up -d
# Wait for MySQL to initialize
sleep 15
# Initialize the Guacamole database
docker exec -i $(docker-compose ps -q guacamole-server) /opt/guacamole/bin/initdb.sh \
    --mysql \
    --users=guac \
    --password=guacpassword \
    --databases=guacamole
echo "Apache Guacamole setup is complete. Access it at http://localhost:8080"
echo "Default username: guacadmin, Default password: guacadmin"
